title: 'Blue Team Victor'
author: 'Victor Fernandez III'
description: 'My blog about tactical cybersecurity operations.'
include:
  - _assets
  - _navigation
  - notes
header_pages:
- _navigation/blog.md
- _navigation/guides.md
- _navigation/downloads.md
- _navigation/about.md
theme: minima
minima:
  social_links:
    linkedin: vicfernandeziii
    github: cyberphor
    twitter: cyberphor
    
# https://dev.to/charalambosioannou/create-a-static-webpage-with-a-contact-form-on-github-pages-3532
