title: cyberphor
tagline: 'Papa/Dad. Soldier. Blue Team benchwarmer.'
description: 'Papa/Dad. Soldier. Blue Team benchwarmer.'
author:
  name: Victor Fernandez III
header_pages:
 - essays.md
 - notes.md
 - guides.md
 - examples.md
 - demos.md
theme: minima
minima:
  date_format: "%Y-%m-%d"
  skin: solarized
  social_links:
    twitter: cyberphor
    github:  cyberphor
    linkedin: vicfernandeziii
markdown: kramdown
kramdown:
  hard_wrap: false
plugins:
 - jekyll-feed
 - jekyll-seo-tag
