title: 'Victor Fernandez III'
author: cyberphor
include:
  - _assets
  - _navigation
  - notes
header_pages:
- _navigation/blog.md
- _navigation/guides.md
theme: minima
minima:
  social_links:
    linkedin: vicfernandeziii
    github: cyberphor
    twitter: cyberphor
