title: 'cyberphor'
author: 'Victor Fernandez III'
description: 'Tactical Cybersecurity Operations'
include:
  - _assets
  - _navigation
  - _downloads
header_pages:
- _navigation/blog.md
- _navigation/downloads.md
- name: Learn2Code
  url: https://learn2code.cyberphor.com
- _navigation/about.md
theme: minima
minima:
  social_links:
    linkedin: vicfernandeziii
    github: cyberphor
    twitter: cyberphor
    
# https://dev.to/charalambosioannou/create-a-static-webpage-with-a-contact-form-on-github-pages-3532
