title: 'cyberphor'
author: 'Victor Fernandez III'
include:
  - _assets
  - _navigation
header_pages:
- _navigation/blog.md
- _navigation/about.md
theme: minima
minima:
  social_links:
    twitter: cyberphor
    github: cyberphor
    linkedin: cyberphor
    reddit: cyberphor

# https://dev.to/charalambosioannou/create-a-static-webpage-with-a-contact-form-on-github-pages-3532
