title: 'cyberphor'
author: 'Victor Fernandez III'
description: 'Tactical Cybersecurity Operations'
include:
  - _assets
  - _navigation
  - _downloads
header_pages:
- _navigation/blog.md
- _navigation/downloads.md
- _navgiation/learn2code.md
- _navigation/about.md
theme: minima
minima:
  social_links:
    twitter: cyberphor
    github: cyberphor
    linkedin: vicfernandeziii

# https://dev.to/charalambosioannou/create-a-static-webpage-with-a-contact-form-on-github-pages-3532
